apiVersion: v1
kind: Pod
metadata:
  name: service-pod
  labels:
    jash: mahesh
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    jash: mahesh
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: alma
spec:
  containers:
  - name: almalinux
    image: almalinux
    command: ["sleep","1000"]